# Code

### Imports

In [ ]:
import pandas as pd
import numpy as np
from task1_utils import generateDataVectors,forward_pass,loss,getConfused,getErrorRate
import matplotlib.pyplot as plt

### Data loading

In [ ]:
features = ["SepalLength",
            "SepalWidth",
            "PetalLength",
            "PetalWidth",
            "Class"]

irisData = pd.read_csv("data/IrisData/iris.data", 
                   names=features)

# Take 30 first samples of each Class for training
train_data = irisData.groupby("Class").head(30)
# For last 30 samles of each Class for training uncomment the line below
# train_data = irisData.groupby("Class").tail(30)

test_data = irisData.drop(train_data.index)
train_data.reset_index(drop=True, inplace=True)
test_data.reset_index(drop=True, inplace=True)

In [ ]:
train_data.head()

In [ ]:
# Generate data vectors
x_train, t_train = generateDataVectors(train_data)
x_test, t_test = generateDataVectors(test_data)


print(x_train.shape, t_train.shape, x_test.shape, t_test.shape)

### Training

In [ ]:
# initialize the weights
np.random.seed(42)

n_features = x_train.shape[0]
n_classes = t_train.shape[0]

W = np.random.randn(n_classes,n_features)
print(W)

In [ ]:
MSE_list = []
alpha = 0.001
iterations = 10**6

for i in range(iterations):
    g = forward_pass(x_train, W)

    MSE = loss(g,t_train)
    MSE_list.append(MSE)

    # Backward pass
    grad_MSE = ((g-t_train)*g*(1-g))@x_train.transpose()

    W -= alpha*grad_MSE

In [ ]:
# Plot the MSE
plt.plot(range(len(MSE_list)), MSE_list)
plt.xlabel("Iteration")
plt.ylabel("Mean Squared Error (MSE)")
plt.title("MSE during training")
plt.grid()
plt.show()

### Prediction

In [ ]:
predictions_train = forward_pass(x_train,W)
predictions_test = forward_pass(x_test,W)

train_conf_matrix = getConfused(predictions_train, t_train)
test_conf_matrix = getConfused(predictions_test, t_test)

print(train_conf_matrix)
print(f"{getErrorRate(train_conf_matrix):.4f}")
print(test_conf_matrix)
print(f"{getErrorRate(test_conf_matrix):.4f}")

# Results

## First 30 used for training, last 20 used for testing:

MSE = 7.898

### Validation with training data:
[30.  0.  0.]\
[ 0. 29.  1.]\
[ 0.  0. 30.]

error rate = 0.0111

### Validation with test data:
[20.  0.  0.]\
[ 0. 19.  1.]\
[ 0.  1. 19.]

error rate = 0.0333

## First 20 used for testing, last 30 used for training:

MSE = 7.545

### Validation with training data:

 [30.  0.  0.]\
 [ 0. 27.  3.]\
 [ 0.  2. 28.]

0.0556


### Validation with test data:

[20.  0.  0.]\
[ 0. 20.  0.]\
[ 0.  1. 19.]

0.0167
